TrabajoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth
from django.conf import settings
from django.conf.urls.static import static
#from .views import SignUpView


from . import views 


urlpatterns = [
    path('admin/', admin.site.urls),

    path('',views.Inicio, name='primera_vista'),
    path('login/', auth.LoginView.as_view(template_name="usuarios/login.html"), name='login'),
    path('logout/', auth.LogoutView.as_view(), name='logout'),
    path('posts/',include('apps.posts.urls')),
    path('register/', views.register, name="register" )
    #path('registro/', registro_usuario name="registro_usuario"),  
    #path('accounts/',include('django.contrib.auth.urls')),
    #path('accounts/',include('registration.urls')),
    #path('signup/', SignUpView.as_view(), name="signup"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/posts/urls.py
from django.urls import path
from . import views 

app_name='posts'

urlpatterns = [
    path('Alta/', views.AltaPost.as_view(),name='alta_post'),
    path('filtro/<int:pk>', views.filtro, name = 'filtro'),
    path('detalle/<int:pk>', views.DetallePost, name= 'detalle'),
]

apps/posts/models.py
from django.db import models

class Ods(models.Model):
	nombre = models.CharField(max_length = 255)
	descripcion = models.TextField(null = True)
	imagen = models.ImageField(upload_to='imagenes_ods', null=True)

	def __str__(self):
		return self.nombre

class Posts(models.Model):
	nombre = models.CharField(max_length=255)
	body = models.TextField(null = True)
	fecha_post = models.DateTimeField(auto_now_add=True, null = True)
	Ods = models.ForeignKey(Ods, on_delete = models.CASCADE)
	imagen = models.ImageField(upload_to='imagenes_posts', null=True)
		
	class Meta:
		ordering = ['-fecha_post']

	def __str__(self):
		return self.nombre

class Comentarios(models.Model):
	Posts = models.ForeignKey(Posts, related_name="comments", on_delete = models.CASCADE)
	name = models.CharField(max_length=255)
	body = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	status = models.BooleanField(default=True)

	class Meta: 
		ordering = ("date_added",)


	def __str__(self):
		return '%s - %s' % (self.Posts.nombre, self.name)

apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
	pass 
	

TrabajoFinal/forms.py
#from django import forms
#from django.contrib.auth.forms import UserCreationForm


#class CustomUserFomr(UserCreationForm):
#	pass
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from apps.usuarios.models import Usuario


class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()
	password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput)

	class Meta:
		model = Usuario
		fields = ['username', 'email', 'password1', 'password2']
		help_texts = {k:"" for k in fields }

apps/posts/forms.py
from django import forms
from django.db.models.fields import CommaSeparatedIntegerField
from django.forms import widgets
from .models import Posts, Comentarios
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from apps.usuarios.models import Usuario


class Formulario_alta_post(forms.ModelForm):
	

	class Meta:
		model = Posts
		fields= '__all__'
		widgets = { 
			"nombre": forms.TextInput(attrs={"class": "form-control" }),
			"Body": forms.Textarea(attrs={"class": "form-control"}),
		}


class NuevoComentario(forms.ModelForm):
	
	class Meta:
		model = Comentarios
		fields= ( "name", "body")
		widgets = {
			"name": forms.TextInput(attrs={"class": "col-sm-12"}),
		    "body": forms.Textarea(attrs={"class": "col-sm-12"}),

		}







		

TrabajoFinal/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm
from apps.posts.models import Ods, Posts

def Inicio(request):
	p = Posts.objects.all()
	ctx = {}
	ctx['posts'] = p

	o = Ods.objects.all()
	ctx['Ods'] = o
	
	return render (request,'Base.html',ctx)



def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			messages.success(request, f'Usuario {username} creado')
			return redirect('login')
	else:
		form = UserRegisterForm()
	context = { 'form' : form }
	return render(request, 'usuarios/register.html', context)

apps/posts/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .models import Ods, Posts, Comentarios
from .forms import Formulario_alta_post, NuevoComentario
# si la vista es basada en funcion
from django.contrib.auth.decorators import login_required

#si la vista es basada en clase
from django.contrib.auth.mixins import LoginRequiredMixin


class AltaPost(LoginRequiredMixin,CreateView):
	model= 'Posts'
	template_name = 'Posts/alta.html'
	form_class = Formulario_alta_post
	success_url= reverse_lazy('primera_vista')


def filtro(request, pk):
	p = Posts.objects.filter(Ods = pk)
	
	ctx = {}
	ctx['posts'] = p
	o = Ods.objects.all()
	ctx['Ods'] = o
	
	return render (request,'Posts/Filtro.html',ctx)	


def DetallePost(request, pk):

	p = Posts.objects.get(pk = pk)
	ctx = {}
	ctx['posts'] = p
	o = Ods.objects.all()
	ctx['Ods'] = o
	comments = p.comments.filter(status=True)
	SoloEstePost = None

	if request.method == 'POST':
		comment_form = NuevoComentario(request.POST,)
		if comment_form.is_valid():
			SoloEstePost = comment_form.save(commit=False)
			SoloEstePost.Posts = p
			SoloEstePost.save()
			
	else:
		comment_form = NuevoComentario()
	return render(request, 'Posts/detallePost.html', {'p': p, 'comments': SoloEstePost, 'comments': comments, 'comment_form': comment_form, 'posts': p, 'Ods': o})

apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.
#from django.contrib.auth.forms import UserCreationForm
#from django.views.generic import CreateView
#from django.urls import reverse_lazy

#class SignUpView(CreateView):
#	form_class = UserCreationForm
#	success_url = reverse_lazy('login')
#	template_name = 'usuarios/register.html'

templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Unless You</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'primera_vista' %}">Unless you</a>	
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" >Bienvenid@ {{ user.username }}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'primera_vista' %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'posts:alta_post' %}">Crear Post</a></li>
                        {% else %}
                             <li class="nav-item"><a class="nav-link" href="{% url 'primera_vista' %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registrate</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">UNLESS YOU</h1>
                    <h2>17 Objetivos de desarrollo sostenible</h2>
                    <p class="lead mb-0">A menos de que vos empieces un cambio..</p>
                    <img src="{% static 'img/Logo.png' %}">
                </div>
            </div>
            
       </header>

    {% block contenido %}

    {% endblock contenido %}

        
    <div class="container">
        <div class="row" style="flex-wrap: wrap-reverse;">
            {% for a in posts %} 
            <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Nested row for non-featured blog posts-->
                    <div class="row">
                        <div class="col-lg-7 ">
                            <!-- Blog post-->
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="{{a.imagen.url}}" alt="..." /></a>
                                <div class="card-body">
                                    <div class="large text-muted">{{a.fecha_post}}</div>
                                    <div class="small text-muted">Objetivo:{{a.Ods}}</div>
                                    <h2 class="card-title h4">{{a.nombre}}</h2>
                                   
                                    <a class="btn btn-primary" href="{% url 'posts:detalle' a.pk %}">Leer más... →</a>
                                </div>                                  
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            
            
            <!-- Side widgets-->
            <div class="col-lg-4 ">
                <!-- Categories widget-->
                <div class="card mb-4">
                    <div class="card-header">Los 17 objetivos!</div>
                    <div class="card-body">
                        <div class=".row">
                            <div class=".col-lg-8">
                                <ul class="list-unstyled mb-0">
                                    {% for o in Ods %}
                                        <li><a href="{% url 'posts:filtro' o.pk%}" style="text-decoration: none;"> {{o.nombre}}</li>
                                    {% endfor %} 
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class= "m-2 text-center text-white"> Copyright- todos los derechos reservados - Argentina - Chaco </p>
        </div>
        <div class="container">
            <div class="row justify-content-center ">
                <div class="col-md-12 text-center justify-content-center">
                    <div class="enlaceRedes">
                        <a href="https://facebook.com"> <img class="facebook" width="25" height="25" margin-right:5rem; #facebook:hover src="{% static 'img/facebook.png' %}"></a>
                        <a href="https://twitter.com"> <img class="twitter" width="25" height="25" margin-right:5rem; src="{% static 'img/twiter.png' %}">
                        </a>
                        <a href="https://instagram.com"> <img class="instagram" width="25" height="25" margin-right:5rem; src="{% static 'img/instagram.png' %}"></a>
                        <a href="https://youtube.com"> <img class="youtube" width="25" height="25" margin-right:5rem; #facebook:hover src="{% static 'img/youtube.png' %}"></a>
                    </div> 
                </div>
            </div>
        </div>
        
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>




</body>
</html>

templates/Posts/Filtro.html
{% extends 'Base.html' %}

templates/Posts/alta.html
{% block contenido %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Unless You</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'primera_vista' %}">Unless you</a>	
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" >Bienvenid@ {{ user.username }}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'primera_vista' %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'posts:alta_post' %}">Crear Post</a></li>
                        {% else %}
                             <li class="nav-item"><a class="nav-link" href="{% url 'primera_vista' %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registrate</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">UNLESS YOU</h1>
                    <h2>17 Objetivos de desarrollo sostenible</h2>
                    <p class="lead mb-0">A menos de que vos empieces un cambio..</p> 
                    <img src="{% static 'img/Logo.png' %}">
                </div>
            </div>
       </header>
	   <h1 class="display-5" style="padding-bottom: 1em;">Aqui abajo puede crear su propio Post!</h1>
			<form method="POST" enctype="multipart/form-data">{% csrf_token %}
				{{form.errors}}
				{{form.as_p}}
				<input class="buttons" type="submit" name="" value="Crear">
			</form>
{% endblock contenido %}

templates/Posts/detallePost.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Unless You</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'primera_vista' %}">Unless you</a>	
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" >Bienvenid@ {{ user.username }}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'primera_vista' %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'posts:alta_post' %}">Crear Post</a></li>
                        {% else %}
                             <li class="nav-item"><a class="nav-link" href="{% url 'primera_vista' %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registrate</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{ posts.nombre }}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Fue creado el dia {{ posts.fecha_post }}</div>
                            <!-- Post categories-->
                            <a class="badge bg-secondary text-decoration-none link-light">{{ posts.Ods }}</a>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="{{posts.imagen.url}}" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{ posts.body }}</p>
                        </section>
                    </article>
                    <figure><strong>      
                        <blockquote class="blockquote">
                          <p>Sección de comentarios</p></strong>
                        </blockquote>
                        <figcaption class="blockquote-footer">
                          Su opinión nos importa
                        </figcaption>
                      </figure>
                <!-- Comments section-->
                <section class="mb-5">
                    {% for comment in comments %}
                    <div class="card bg-light">
                        <div class="card-body">
                            <!-- Single comment-->
                            <div class="d-flex">
                                <div class="ms-3">Comentado el dia: {{comment.date_added}}
                                    <div class="fw-bold">{{comment.name}}</div>
                                    {{comment.body}}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </section>
            </div>
            <!-- Side widgets-->
            <div class="col-lg-4">
                <!-- Search widget-->
                <div class="card mb-4">
                    <div class="card-header">Los 17 objetivos!</div>
                    <div class="card-body">
                        <div class=".row">
                            <div class=".col-lg-8">
                                <ul class="list-unstyled mb-0">
                                    {% for o in Ods %}
                                        <li><a href="{% url 'posts:filtro' o.pk%}" style="text-decoration: none;">{{o.nombre}}</a></li>
                                    {% endfor %} 
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    {% if user.is_authenticated %}        
    <h2 class="display-5">Hacer un nuevo comentario</h2> 
         
    <form id="myForm" method="POST">
        {{comment_form.as_p}}
        {% csrf_token %}
        <button type='submit' class="btn - btn-primary btn-lg btn-block"> Comentar </button>
    </form>
    {% else %}
    <h3 class="Display-5">Inicia sesión para poder comentar.</h3>
    <a class="nav-link" href="{% url 'login' %}">Login</a>
    <a class="nav-link" href="{% url 'register' %}">Registrate</a>
    {% endif %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class= "m-2 text-center text-white"> Copyright- todos los derechos reservados - Argentina - Chaco </p>
            </div>
            <div class="container">
                <div class="row justify-content-center ">
                    <div class="col-md-12 text-center justify-content-center">
                        <div class="enlaceRedes">
                            <a href="https://facebook.com"> <img class="facebook" width="25" height="25" margin-right:5rem; #facebook:hover src="{% static 'img/facebook.png' %}"></a>
                            <a href="https://twitter.com"> <img class="twitter" width="25" height="25" margin-right:5rem; src="{% static 'img/twiter.png' %}">
                            </a>
                            <a href="https://instagram.com"> <img class="instagram" width="25" height="25" margin-right:5rem; src="{% static 'img/instagram.png' %}"></a>
                            <a href="https://youtube.com"> <img class="youtube" width="25" height="25" margin-right:5rem; #facebook:hover src="{% static 'img/youtube.png' %}"></a>
                        </div> 
                    </div>
                </div>
            </div>


            
            
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/usuarios/login.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title> Login </title>
		{% load static %}

		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<body bgcolor="#add8e6">
	</head>
	<body>
		<div class="login-box">
		<img src="{% static 'img/ll.png' %}" class="avatar" style="width: 100px; height: 100px; border-radius: 50%;position: absolute; top: -50px; left: calc(50% - 50px);">
      	<h1>Login</h1>
      	<form method="POST" class="formulario">{% csrf_token %}
				{{form.errors}}
        <!-- USERNAME INPUT -->
        <label for="username"> Usuario </label>
        <input class="controls" type="text" name="username" placeholder="USUARIO">
        <!-- PASSWORD INPUT -->
        <label for="password">Contraseña</label>
        <input class="controls" type="password" name="password" placeholder="CONTRASEÑA">
        <input class="buttons" type="submit" name="" value="Ingresar">
        <a href="{% url 'primera_vista' %}"> VOLVER AL INICIO </a>
      </form>
    </div>
	</body>
</html>
			
			
			
		

templates/usuarios/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Register</title>
	


    <body bgcolor= #add8e6>

</head>
<body>

	<h1 style="text-align: center; padding-top: 100px; font-family: Arial;">Registro de Usuario</h1>
	<div class="caja">
		<form action="" method="post">{% csrf_token %}
		<div style="margin-top: 0px;">	
		{% for field in form %}
			<div class="field_container" style="text-align: center; padding-top: 20px; font-family: Arial;">
				{{ field.errors }}
				{{ field.label_tag }} </br>
				{{ field }}
				
			</div>	

		{% endfor %}
			
		</div>	
			


			<p style="text-align: center;">
			<input type="submit" value="Registrar">
			</p>
			

		</form>
		<form action="{% url 'primera_vista' %}" method="get" style="text-align: center;">
 			<button type="submit">Volver al Inicio<br /></button></form>
			
	</div>
	{% if messages %}
			{% for message in messages %}
			<div class="notification {{ message.tags}}">
				{{ message }}
			</div>
			{% endfor %}
	{% endif %}
</body>
</html>